#!/usr/bin/env sh
#MISE description="Reboot the DigitalOcean Ubuntu test VM"
set -eu
doctl compute droplet-action reboot "$(doctl compute droplet list "$DROPLET_NAME" --format ID --no-header)" --wait
