---
- import_playbook: require-ubuntu-release.yml
- import_playbook: ensure-admin-ssh-key.yml
- import_playbook: lockdown-ssh.yml
- import_playbook: enable-unattended-upgrades.yml
- import_playbook: update-ubuntu-packages.yml
- import_playbook: install-tailscale.yml
- import_playbook: join-tailscale.yml
