#!/usr/bin/env sh
#MISE description="Converge the local QEMU Ubuntu test VM over ansible SSH"
set -eu
. "$MISE_CONFIG_ROOT/mise-tasks/lib.sh"
ssh_task_preamble

qemu_ansible_playbook "$MISE_CONFIG_ROOT/collection/playbooks/converge.yml"
