---
- name: Initialize baseline users
  hosts: all
  become: true
  gather_facts: false

  vars:
    baseline_users_ansible_public_key_file: >-
      {{
        baseline_ansible_public_key_file |
        default(lookup('ansible.builtin.env', 'ANSIBLE_SSH_PUBLIC_KEY_RENDERED'), true)
      }}
    baseline_users_admin_public_key_file: >-
      {{
        baseline_admin_public_key_file |
        default(lookup('ansible.builtin.env', 'ADMIN_USER_SSH_PUBLIC_KEY_RENDERED'), true)
      }}

  tasks:
    # ==========================================================================
    # Inputs
    # ==========================================================================
    - name: Check ansible public key file path
      ansible.builtin.assert:
        that:
          - baseline_users_ansible_public_key_file | default("") | length > 0
        fail_msg: "Set baseline_ansible_public_key_file or ANSIBLE_SSH_PUBLIC_KEY_RENDERED."

    - name: Check admin public key file path
      ansible.builtin.assert:
        that:
          - baseline_users_admin_public_key_file | default("") | length > 0
        fail_msg: "Set baseline_admin_public_key_file or ADMIN_USER_SSH_PUBLIC_KEY_RENDERED."

    # ==========================================================================
    # Ansible User
    # ==========================================================================
    - name: Add ansible passwordless sudo user
      ansible.builtin.import_tasks: tasks/add-passwordless-sudo-user.yml
      vars:
        user_name: ansible

    - name: Install ansible Ed25519 authorized key
      ansible.builtin.import_tasks: tasks/install-ssh-authorized-key.yml
      vars:
        user_name: ansible
        public_key: "{{ lookup('ansible.builtin.file', baseline_users_ansible_public_key_file) | trim }}"

    # ==========================================================================
    # Admin User
    # ==========================================================================
    - name: Add admin passwordless sudo user
      ansible.builtin.import_tasks: tasks/add-passwordless-sudo-user.yml
      vars:
        user_name: admin

    - name: Install admin Ed25519 authorized key
      ansible.builtin.import_tasks: tasks/install-ssh-authorized-key.yml
      vars:
        user_name: admin
        public_key: "{{ lookup('ansible.builtin.file', baseline_users_admin_public_key_file) | trim }}"

- import_playbook: validate-ssh-sudo-access.yml
