#!/usr/bin/env sh
#MISE description="Block until first-boot cloud-init is done on the QEMU VM (next: qemu:play:converge)"
set -eu
. "$MISE_CONFIG_ROOT/mise-tasks/lib.sh"

qemu_probe() {
  qemu_ssh ansible "$ANSIBLE_PUB_KEY" "$@"
}

wait_for_cloud_init qemu_probe
