---
- import_playbook: add-ssh-sudo-user.yml
  vars:
    user_name: ansible
    public_key_file: >-
      {{
        baseline_ansible_public_key_file |
        default(lookup('ansible.builtin.env', 'ANSIBLE_SSH_PUBLIC_KEY_RENDERED'), true)
      }}

- import_playbook: add-ssh-sudo-user.yml
  vars:
    user_name: admin
    public_key_file: >-
      {{
        baseline_admin_public_key_file |
        default(lookup('ansible.builtin.env', 'ADMIN_USER_SSH_PUBLIC_KEY_RENDERED'), true)
      }}

- import_playbook: validate-ssh-sudo-access.yml
