#!/usr/bin/env sh
#MISE description="Delete the bootstrap SSH public key from DigitalOcean"
#MISE confirm="Delete the bootstrap SSH public key from DigitalOcean? This cannot be undone."
set -eu
bootstrap_key_id="$(doctl compute ssh-key list --output json | jq -r --arg name "$DO_BOOTSTRAP_KEY_NAME" '.[] | select(.name == $name) | .id')"

doctl compute ssh-key delete "$bootstrap_key_id" --force
