#!/usr/bin/env sh
# Render the baseline cloud-init user-data for the DigitalOcean Ubuntu host.
#
# Reads the extracted public keys under .generated/ssh (produced by
# `mise run key:extract`) and writes the cloud-config to .generated/cloud-init.
# Depends only on files under .generated, never on 1Password.
#
# Required environment (supplied by mise): ANSIBLE_PUB_KEY, ADMIN_PUB_KEY,
# CLOUD_INIT_FILE. Run via `mise run cloud-init:render`.
set -eu

if [ ! -s "$ANSIBLE_PUB_KEY" ] || [ ! -s "$ADMIN_PUB_KEY" ]; then
  echo "Missing extracted public keys. Run 'mise run key:extract' first." >&2
  exit 1
fi

ansible_pubkey="$(cat "$ANSIBLE_PUB_KEY")"
admin_pubkey="$(cat "$ADMIN_PUB_KEY")"

mkdir -p "$(dirname "$CLOUD_INIT_FILE")"

# Unquoted heredoc: only $ansible_pubkey and $admin_pubkey expand; the rest is
# literal. Keep this body free of other shell-style variable references.
cat > "$CLOUD_INIT_FILE" <<EOF
#cloud-config
# Generated by playbooks/cloud-init/render.sh from .generated/ssh/*.pub.
# Do not edit this file; edit the generator script instead.

# Keep DigitalOcean's default root user reachable via the bootstrap key
# (injected with --ssh-keys) as a break-glass path.
disable_root: false
ssh_pwauth: false

users:
  - default
  - name: ansible
    shell: /bin/bash
    lock_passwd: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "$ansible_pubkey"
  - name: admin
    shell: /bin/bash
    lock_passwd: true
    # Ubuntu images ship a pre-existing "admin" group, so do not create a
    # same-named user-private-group (useradd would fail with exit code 9).
    no_user_group: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "$admin_pubkey"

write_files:
  - path: /etc/ssh/sshd_config.d/10-ubuntu-baseline.conf
    owner: "root:root"
    permissions: "0644"
    content: |
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PubkeyAuthentication yes
      PermitRootLogin prohibit-password
      X11Forwarding no
      ClientAliveInterval 300
      ClientAliveCountMax 2

runcmd:
  # Ensure the privilege-separation dir exists so sshd -t can validate this
  # early in boot, then fail loudly on a bad config and apply it (socket-
  # activated on 24.04, service otherwise).
  - mkdir -p /run/sshd
  - /usr/sbin/sshd -t
  - systemctl reload ssh.service 2>/dev/null || systemctl try-restart ssh.socket || true
EOF

echo "Rendered $CLOUD_INIT_FILE"
