---
- import_playbook: lockdown-ssh.yml
- import_playbook: configure-unattended-upgrades.yml
- import_playbook: update-ubuntu-packages.yml
- import_playbook: install-tailscale.yml
- import_playbook: install-osquery.yml
- import_playbook: install-lynis.yml
