---
# ==========================================================================
# SSH Access
# ==========================================================================
- name: Install SSH public key
  ansible.posix.authorized_key:
    user: "{{ ubuntu_user_name }}"
    key: "{{ ubuntu_user_public_key }}"
    state: present
    manage_dir: true
