#!/usr/bin/env sh
#MISE description="Who can get in? Read-only; always changed=0"
set -eu
. "$MISE_CONFIG_ROOT/mise-tasks/lib.sh"
ssh_task_preamble

ansible-playbook \
  -i "$(droplet_ip)," \
  "$MISE_CONFIG_ROOT/collection/playbooks/report_access.yml"
