#!/usr/bin/env sh
#MISE description="From zero: vm:create -> vm:wait -> play:converge"
set -eu
mise run do:vm:create
mise run do:vm:wait
mise run do:play:converge
echo "Droplet lab is up and converged."
