#!/usr/bin/env sh
# Render the baseline cloud-init user-data for the Ubuntu host (RFC-006: Provisioning).
#
# cloud-init establishes access and patches the OS; the Ansible roles remain the
# single source of truth for the full baseline. This script reproduces only the
# file-shaped controls the roles own -- the two access accounts, their per-user
# sudoers, and the sshd drop-in -- from the *same sources*, so the first converge
# is a no-op for users and SSH hardening (RFC-006: Provisioning).
#
# Reads the extracted public keys under .generated/ssh (produced by
# `mise run key:prep`) and the role-owned sshd drop-in; writes the
# cloud-config to CLOUD_INIT_FILE. Depends only on files in the repo and under
# .generated, never on 1Password.
#
# Required environment (supplied by mise): ANSIBLE_PUB_KEY, SYSADMIN_PUB_KEY,
# CLOUD_INIT_FILE. Run via `mise run cloud-init:render`.
set -eu

if [ ! -s "$ANSIBLE_PUB_KEY" ] || [ ! -s "$SYSADMIN_PUB_KEY" ]; then
  echo "Missing public key files: point ANSIBLE_PUB_KEY and SYSADMIN_PUB_KEY at your extracted public keys." >&2
  exit 1
fi

collection_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
sshd_dropin="$collection_root/roles/ssh/files/10-ubuntu-baseline.conf"

if [ ! -s "$sshd_dropin" ]; then
  echo "Missing sshd drop-in source: $sshd_dropin" >&2
  exit 1
fi

ansible_pubkey="$(cat "$ANSIBLE_PUB_KEY")"
sysadmin_pubkey="$(cat "$SYSADMIN_PUB_KEY")"

mkdir -p "$(dirname "$CLOUD_INIT_FILE")"

# Unquoted heredoc: $ansible_pubkey, $sysadmin_pubkey and the $(sed ...) that
# embeds the role-owned sshd drop-in expand; everything else is literal. Keep
# this body free of other shell-style variable references.
cat > "$CLOUD_INIT_FILE" <<EOF
#cloud-config
# Generated by collection/scripts/render-cloud-init.sh. Do not edit this file; edit the
# generator script and the role-owned sources it reads.

ssh_pwauth: false

# cloud-init establishes access only. The Ansible roles own and enforce the full
# baseline; these accounts and files are reproduced from the same sources so the
# first converge is a no-op for users and SSH hardening.
#
# Exactly the two baseline accounts, nothing else: no '- default' entry
# (the image's default user would be unowned residue on every
# non-provider platform) and no 'disable_root' override. The provider's
# own bootstrap door -- a key injected by provider machinery outside this
# user-data -- is the provider's business: observed by the access report,
# closed by a deliberate lock (RFC-006: Provisioning).
users:
  - name: ansible
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - "$ansible_pubkey"
  - name: sysadmin
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - "$sysadmin_pubkey"

write_files:
  # Sudoers via write_files, NOT the users: \`sudo:\` directive, on purpose:
  #   - cloud-init's \`sudo:\` shortcut writes ONE combined file,
  #     /etc/sudoers.d/90-cloud-init-users;
  #   - roles/users instead manages per-user files, /etc/sudoers.d/<name>.
  # Writing the same per-user files here makes cloud-init and the role produce
  # byte-identical artifacts. Why we bother: the first converge then sees no
  # sudo change, no orphan 90-cloud-init-users file is left behind, and
  # \`converge --check\` drift detection is trustworthy from first boot.
  # (The alternative -- the simpler \`sudo:\` directive -- would leave a redundant
  # cloud-init sudoers file the role does not manage.)
  # Trade-off: keep this content in lockstep with
  # roles/users/tasks/configure-user.yml.
  - path: /etc/sudoers.d/ansible
    owner: "root:root"
    permissions: "0440"
    content: |
      ansible ALL=(ALL) NOPASSWD:ALL
  - path: /etc/sudoers.d/sysadmin
    owner: "root:root"
    permissions: "0440"
    content: |
      sysadmin ALL=(ALL) NOPASSWD:ALL
  # sshd baseline drop-in, embedded from the SAME role-owned source the role
  # deploys (roles/ssh/files/10-ubuntu-baseline.conf) -- same single-source
  # reasoning as the sudoers above, so converge sees no change for it either.
  - path: /etc/ssh/sshd_config.d/10-ubuntu-baseline.conf
    owner: "root:root"
    permissions: "0644"
    content: |
$(sed 's/^/      /' "$sshd_dropin")

# Bring the stale provider image up to current: package_upgrade runs
# apt-get dist-upgrade (a full upgrade, including a new kernel), then reboot
# unconditionally. The reboot activates the new kernel AND is a smoke test --
# converge can only connect afterward if the host came back with working SSH,
# so a successful first converge proves the box survives a reboot. (The fuller
# reboot-survivability acceptance test lives in the roles, per RFC-009: Validation and Acceptance.)
# No runcmd: the drop-in is static and role-validated, and the reboot re-reads
# it, so an sshd -t diagnostic / reload here would add nothing.
package_update: true
package_upgrade: true

power_state:
  mode: reboot
  condition: true
  message: First-boot reboot after upgrade (activates kernel; confirms host returns)
EOF

# cloud-config must be pure ASCII: DigitalOcean's config-drive metadata pipeline
# can mangle a multi-byte UTF-8 char (e.g. an em-dash) into a byte YAML rejects,
# which silently poisons the whole document and drops every user. Fail loudly
# rather than ship a broken image.
if LC_ALL=C grep -q '[^ -~]' "$CLOUD_INIT_FILE"; then
  echo "Rendered cloud-config contains non-ASCII characters; it must be ASCII-only." >&2
  exit 1
fi

echo "Rendered $CLOUD_INIT_FILE"
